name: infra-plan
on:
  pull_request:
    paths:
      - 'infra/terraform/**'
      - 'infra/eks/**'
      - '.github/workflows/infra-plan.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - uses: azure/setup-helm@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          framework: terraform
          soft_fail: false
      - name: terraform init
        working-directory: infra/terraform/envs/prod
        run: terraform init -backend-config=backend.hcl
      - name: terraform plan
        working-directory: infra/terraform/envs/prod
        run: terraform plan -no-color -out=tfplan

      - name: terraform init (eks add-ons)
        working-directory: infra/eks
        run: terraform init

      - name: terraform plan (eks add-ons)
        working-directory: infra/eks
        run: terraform plan -no-color -out=tfplan
